RedisAddressParam = "docker.vm:6379"
RedisPasswordParam = ""
RedisDbParam = 0

RedisAdressData = "docker.vm:6379"
RedisPasswordData = ""
RedisDbData = 10


JwtSecret = "WyBJujUQzWg4YiQqLe9N36DA/8QqZcOkg2o="
MaxBufferSize = 33000000
CORS = "*"
